SELECT *
FROM PS_REVIEW
;

SELECT *
FROM PET_BREED
;

DESC BOARD
;

CREATE TABLE MEMBER_WITHDRAW
( MEMBER_CODE_SEQ   VARCHAR2(40) NOT NULL           -- 회원등록코드
, WITHDRAW_DATE     DATE DEFAULT SYSDATE NOT NULL   -- 탈퇴일
, CONSTRAINT MEMBER_WITHDRAW_SEQ_FK FOREIGN KEY(MEMBER_CODE_SEQ)
             REFERENCES MEMBER_CODE(SEQ)
);


-- 시퀀스 초기화 시키기
/*
SELECT LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'MEMBER_REG_SEQ';  -- 현재 값 확인
ALTER SEQUENCE MEMBER_REG_SEQ INCREMENT BY 15; -- 현재 값 만큼 뺌
SELECT MEMBER_REG_SEQ.NEXTVAL FROM DUAL; -- 시퀀스의 NEXTVAL 값 조회
ALTER SEQUENCE MEMBER_REG_SEQ INCREMENT BY 1;    -- 증가값을 다시 1로 설정
*/



-- 제약조건이 참조하는 부모테이블명 찾기
SELECT FK.CONSTRAINT_NAME "제약조건명"
     , FK.TABLE_NAME "자식테이블"
     , FC.COLUMN_NAME "자식컬럼"
     , PK.TABLE_NAME "부모테이블"
     , PC.COLUMN_NAME "부모컬럼"
FROM ALL_CONSTRAINTS FK, ALL_CONSTRAINTS PK
   , ALL_CONS_COLUMNS FC, ALL_CONS_COLUMNS PC
WHERE FK.R_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
  AND FK.CONSTRAINT_NAME = FC.CONSTRAINT_NAME
  AND PK.CONSTRAINT_NAME = PC.CONSTRAINT_NAME
  AND FK.CONSTRAINT_TYPE = 'R'
  AND PK.CONSTRAINT_TYPE = 'P'
  AND FK.TABLE_NAME = '자식테이블의 테이블명';
  
  
-- 부모테이블의 PK를 참조하는 자식테이블 찾기
SELECT FK.CONSTRAINT_NAME "제약조건명"
     , FK.TABLE_NAME "자식테이블"
     , FC.COLUMN_NAME "자식컬럼"
     , PK.TABLE_NAME "부모테이블"
     , PC.COLUMN_NAME "부모컬럼"
FROM ALL_CONSTRAINTS FK, ALL_CONSTRAINTS PK
   , ALL_CONS_COLUMNS FC, ALL_CONS_COLUMNS PC
WHERE FK.R_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
  AND FK.CONSTRAINT_NAME = FC.CONSTRAINT_NAME
  AND PK.CONSTRAINT_NAME = PC.CONSTRAINT_NAME
  AND FK.CONSTRAINT_TYPE = 'R'
  AND PK.CONSTRAINT_TYPE = 'P'
  AND PK.TABLE_NAME = 'DIARY_CONTENT';

-- ON DELETE CASCADE 제약조건 추가 쿼리
/*
-- 1. 기존 제약조건 삭제
ALTER TABLE 자식테이블명
DROP CONSTRAINT 제약조건명;

ALTER TABLE REPLY
DROP CONSTRAINT REPLY_BOARD_FK;
-- 2. 새로운 제약조건 생성
ALTER TABLE 자식테이블명
ADD CONSTRAINT 제약조건명 FOREIGN KEY(자식테이블의컬럼명)
REFERENCES 부모테이블명(부모테이블의PK컬럼명)
ON DELETE CASCADE;

ALTER TABLE 자식테이블명
ADD CONSTRAINT 제약조건명 FOREIGN KEY(자식테이블의컬럼명)
REFERENCES 부모테이블명(부모테이블의PK컬럼명)
ON DELETE CASCADE;

-- 게시글 삭제 시 댓글도 함께 삭제될 수 있도록 ON DELETE CASCADE 제약조건 추가
/*
ALTER TABLE REPLY
DROP CONSTRAINT REPLY_BOARD_FK;

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(BOARD_SEQ)
REFERENCES BOARD(SEQ)
ON DELETE CASCADE;
*/
-- 게시글 삭제 시 첨부 파일도 함께 삭제될 수 있도록 ON DELETE CASCADE 제약조건 추가
/*
ALTER TABLE BOARD_IMG
DROP CONSTRAINT BOARD_IMG_BOARD_FK;

ALTER TABLE BOARD_IMG
ADD CONSTRAINT BOARD_IMG_BOARD_FK FOREIGN KEY(BOARD_SEQ)
REFERENCES BOARD(SEQ)
ON DELETE CASCADE;
*/
-- 게시글 삭제 시 신고 내역도 함께 삭제될 수 있도록 ON DELETE CASCADE 제약조건 추가
/*
ALTER TABLE BOARD_REPORT
DROP CONSTRAINT BOARD_REPORT_BOARD_FK;

ALTER TABLE BOARD_REPORT
ADD CONSTRAINT BOARD_REPORT_BOARD_FK FOREIGN KEY(BOARD_SEQ)
REFERENCES BOARD(SEQ)
ON DELETE CASCADE;

ALTER TABLE BOARD_REPORT_BLIND
DROP CONSTRAINT BOARD_REP_BD_BOARD_REPORT_FK;

ALTER TABLE BOARD_REPORT_BLIND
ADD CONSTRAINT BOARD_REP_BD_BOARD_REPORT_FK FOREIGN KEY(BOARD_REPORT_SEQ)
REFERENCES BOARD_REPORT(SEQ)
ON DELETE CASCADE;

ALTER TABLE BOARD_REPORT_REF
DROP CONSTRAINT BOA_REP_REF_BOARD_REPORT_FK;

ALTER TABLE BOARD_REPORT_REF
ADD CONSTRAINT BOA_REP_REF_BOARD_REPORT_FK FOREIGN KEY(BOARD_REPORT_SEQ)
REFERENCES BOARD_REPORT(SEQ)
ON DELETE CASCADE;
*/
-- 댓글 삭제 시 신고 내역도 함께 삭제될 수 있도록 ON DELETE CASCADE 제약조건 추가
/*
ALTER TABLE REPLY_REPORT
DROP CONSTRAINT REPLY_REPORT_REPLY_FK;

ALTER TABLE REPLY_REPORT
ADD CONSTRAINT REPLY_REPORT_REPLY_FK FOREIGN KEY(REPLY_SEQ)
REFERENCES REPLY(SEQ)
ON DELETE CASCADE;

ALTER TABLE REPLY_REPORT_BLIND
DROP CONSTRAINT PLY_REP_BLINED_REPLY_REPORT_FK;

ALTER TABLE REPLY_REPORT_BLIND
ADD CONSTRAINT PLY_REP_BLINED_REPLY_REPORT_FK FOREIGN KEY(REPLY_REPORT_SEQ)
REFERENCES REPLY_REPORT(SEQ)
ON DELETE CASCADE;

ALTER TABLE REPLY_REPORT_REF
DROP CONSTRAINT PLY_REP_REF_REPLY_REPORT_FK;

ALTER TABLE REPLY_REPORT_REF
ADD CONSTRAINT PLY_REP_REF_REPLY_REPORT_FK FOREIGN KEY(REPLY_REPORT_SEQ)
REFERENCES REPLY_REPORT(SEQ)
ON DELETE CASCADE;
*/
SELECT FK.CONSTRAINT_NAME "제약조건명"
     , FK.TABLE_NAME "자식테이블"
     , FC.COLUMN_NAME "자식컬럼"
     , PK.TABLE_NAME "부모테이블"
     , PC.COLUMN_NAME "부모컬럼"
FROM ALL_CONSTRAINTS FK, ALL_CONSTRAINTS PK
   , ALL_CONS_COLUMNS FC, ALL_CONS_COLUMNS PC
WHERE FK.R_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
  AND FK.CONSTRAINT_NAME = FC.CONSTRAINT_NAME
  AND PK.CONSTRAINT_NAME = PC.CONSTRAINT_NAME
  AND FK.CONSTRAINT_TYPE = 'R'
  AND PK.CONSTRAINT_TYPE = 'P'
  AND FK.TABLE_NAME = 'REPLY_REPORT_REF';

-- 알림 종류 테이블 컬럼 추가 - URL이름
ALTER TABLE NOTIFY_TYPE ADD URL_NAME VARCHAR2(50);
-- 알림 테이블 컬럼 추가 - 알림처리참고코드
ALTER TABLE NOTIFY ADD REFERENCE_CODE VARCHAR2(40);

-- 알림 테이블 컬럼 제거
ALTER TABLE NOTIFY DROP COLUMN CONTENT;






