SELECT USER
FROM DUAL;
--==>> SYS


CREATE USER PETTOPIA
IDENTIFIED BY thor;
--==>> User PETTOPIA이(가) 생성되었습니다.

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO PETTOPIA;
--==>> Grant을(를) 성공했습니다.
-- PETTOPIA 에게 접속, 자원, 테이블스페이스에 용량 제한없음 권한을 부여


ALTER USER PETTOPIA DEFAULT TABLESPACE USERS;
--==>> User PETTOPIA(가) 변경되었습니다.

ALTER USER PETTOPIA TEMPORARY TABLESPACE TEMP;
--==>> User PETTOPIA(가) 변경되었습니다.

DROP USER pettopia CASCADE;

PURGE RECYCLEBIN;

GRANT CREATE VIEW TO PETTOPIA;
