--● 펫시터 프로필 등록 프로시저
CREATE OR REPLACE PROCEDURE PRC_PS_REG_PROCEDURE
( V_CODE    IN PS_REG_VIEW.CODE%TYPE
, V_STATE   IN PS_REG_VIEW.STATE%TYPE )
IS
    -- 선언부
    V_PROCEDURE_DATE    DATE; -- 처리일시를 저장할 변수
    V_MANAGER           MANAGER.NICK%TYPE;       -- 처리 담당자를 저장할 변수
BEGIN
    --실행부
    
    IF (V_STATE='승인') THEN
        --○ 펫시터 신청 승인된 경우 SELECT 쿼리문
        SELECT PSREG.PSREGDATE, MG.NICK INTO V_PROCEDURE_DATE, V_MANAGER
        FROM PS_REG PSREG LEFT JOIN MANAGER MG
        ON PSREG.MANAGER_SEQ = MG.SEQ;
    ELSIF (V_STATE='반려') THEN
        --○ 펫시터 신청 반려된 경우 SELECT 쿼리문
        SELECT PSREF.PSREGREFDATE, MG.NICK INTO V_PROCEDURE_DATE, V_MANAGER
        FROM PS_REG_REF PSREF LEFT JOIN MANAGER MG
        ON PSREF.MANAGER_SEQ = MG.SEQ;
    ELSE
        --○ 펫시터 신청 처리되지 않은 경우 SELECT 쿼리문
        V_PROCEDURE_DATE := NULL;
        V_MANAGER := NULL;
    END IF;
    
    -- PS_REG_VIEW 에 데이터 넣기 (처리일시, 처리담당)
    UPDATE PS_REG_VIEW
    SET PROCEDURE_DATE=V_PROCEDURE_DATE, MANAGER=V_MANAGER
    WHERE CODE=V_CODE;
END;

-- 펫시터프로필코드, 펫시터코드, 돌봄형태, 자기소개상세내용,
-- 우편번호, 주소1, 주소2, 주소3, 공개여부, 은행코드, 계좌번호, 예금주명, 프로필작성일
SELECT *
FROM PS_PROFILE;

-- 입력받는 내용
-- 이용서비스(돌봄형태), 자기소개상세내용, 펫시터주소, 프로필공개여부, 은행코드, 예금주명, 계좌번호
--> DAO.XML 에서 PS_PROFILE 테이블에 <insert> 
-- 이용서비스(돌봄환경)
--> DAO.XML 에서 PS_SERVICE_INFO 테이블(이용 서비스)에 <insert>
-- 돌봄환경이미지
--> DAO.XML 에서 PS_IMG_REG 테이블(돌봄환경 이미지 등록)에 <insert> 

















--회원가입 프로시저(민하)
CREATE OR REPLACE PROCEDURE PRC_JOIN
( V_ID       IN MEMBER_REG.ID%TYPE
, V_PW       IN MEMBER_REG.PW%TYPE
, V_SSN      IN MEMBER_REG.SSN%TYPE
, V_NICK     IN MEMBER_REG.NICK%TYPE
, V_ADDRNUMBER   IN MEMBER_REG.ADDRNUMBER%TYPE
, V_ADDR1   IN MEMBER_REG.ADDR1%TYPE
, V_ADDR2   IN MEMBER_REG.ADDR2%TYPE
, V_ADDR3   IN MEMBER_REG.ADDR3%TYPE
, V_EMAIL   IN MEMBER_REG.EMAIL%TYPE
, V_PHONENUMBER     IN MEMBER_REG.PHONENUMBER%TYPE
)
IS
    V_MEMBER_CODE_SEQ  MEMBER_CODE.SEQ%TYPE;
BEGIN
   --회원고유코드테이블에 INSERT
    INSERT INTO MEMBER_CODE(SEQ, IP, REGDATE) 
    VALUES('MEM-'||LPAD(MEMBER_CODE_SEQ.NEXTVAL,6,'0'),'211.238.142.151', SYSDATE);
    
    COMMIT;
    
    --회원 고유 테이블에서 가장 큰 SEQ 받아오기 
    SELECT MAX(SEQ) INTO V_MEMBER_CODE_SEQ
    FROM MEMBER_CODE; 
    
    --회원등록 테이블에 INSERT
    INSERT INTO MEMBER_REG(SEQ, MEMBER_CODE_SEQ, ID, PW, SSN, NICK, ADDRNUMBER, ADDR1, ADDR2, ADDR3, EMAIL, PHONENUMBER) 
    VALUES('MBR-'||LPAD(MEMBER_REG_SEQ.NEXTVAL,6,'0'), V_MEMBER_CODE_SEQ, V_ID, V_PW, V_SSN, V_NICK, V_ADDRNUMBER, V_ADDR1, V_ADDR2, V_ADDR3, V_EMAIL, V_PHONENUMBER );
    
    --이용약관 동의 테이블에 INSERT
    INSERT INTO PROMISE_AGREE(MEMBER_CODE_SEQ, PROMISE_SEQ , AGREE, AGREEDATE)
    VALUES(V_MEMBER_CODE_SEQ, 1 ,  0, SYSDATE);
    
    INSERT INTO PROMISE_AGREE(MEMBER_CODE_SEQ, PROMISE_SEQ, AGREE, AGREEDATE )
    VALUES(V_MEMBER_CODE_SEQ, 2, 0, SYSDATE );
    
    COMMIT;    
END;

















CREATE OR REPLACE PROCEDURE PRC_WALK_MEETING
( 
 V_WALK_NOP_SEQ        IN WALK_MEETING.WALK_NOP_SEQ%TYPE
, V_WALK_AIM_SEQ        IN WALK_MEETING.WALK_AIM_SEQ%TYPE
, V_REGION_MID_SEQ      IN WALK_MEETING.REGION_MID_SEQ%TYPE
, V_PET_CON_REG_SEQ     IN WALK_MEETING.PET_CON_REG_SEQ%TYPE
, V_PET_SIZE_SEQ        IN WALK_MEETING.PET_SIZE_SEQ%TYPE
, V_WALKTITLE           IN WALK_MEETING.WALKTITLE%TYPE
, V_WALKDATE            IN WALK_MEETING.WALKDATE%TYPE
, V_WALKPLACE           IN WALK_MEETING.WALKPLACE%TYPE
, V_VIEWS               IN WALK_MEETING.VIEWS%TYPE
, V_GENDER_OP_SEQ       IN WALK_MEETING.GENDER_OP_SEQ%TYPE
, V_AGE_OP_SEQ          IN WALK_MEETING.AGE_OP_SEQ%TYPE
, V_CONTENTS            IN WALK_MEETING.CONTNETS%TYPE
)
IS
    V_WALK_MEETING_SEQ  WALK_MEETING.SEQ%TYPE;
BEGIN
   
    V_WALK_MEETING_SEQ := 'WMT-'||LPAD(WALK_MEETING_SEQ.NEXTVAL,6,'0');
    
    --산책모임테이블에 INSERT
    INSERT INTO WALK_MEETING(SEQ,WALK_NOP_SEQ,WALK_AIM_SEQ,REGION_MID_SEQ,PET_CON_REG_SEQ,PET_SIZE_SEQ,
                          WALKTITLE,WALKDATE,WALKPLACE,WRITEDATE,VIEWS,GENDER_OP_SEQ, AGE_OP_SEQ,CONTENTS)
    VALUES(V_WALK_MEETING_SEQ,V_WALK_NOP_SEQ, V_WALK_AIM_SEQ,V_REGION_MID_SEQ,V_PET_CON_REG_SEQ
            ,V_PET_SIZE_SEQ,V_WALKTITLE,to_date(V_WALKDATE,'YYYY-MM-DD HH24:MI')
            ,V_WALKPLACE,SYSDATE,0,V_GENDER_OP_SEQ,V_AGE_OP_SEQ,V_CONTENTS );
    
    
    
    --산책참여 테이블에 INSERT
    INSERT INTO WALK_JOIN(SEQ, WALK_MEETING_SEQ, PET_CON_REG_SEQ)
    VALUES(WALK_JOIN_SEQ.NEXTVAL,V_WALK_MEETING_SEQ,V_PET_CON_REG_SEQ);
    
     COMMIT;     
END;